### PR TITLE
extras: reorganized, added Widows Terminal, added tmux

### PR DESCRIPTION
**Pull request by crzdg**
Added some extras I use myself,

- simple file mapping HEX colors with the color name for use in `tmux`, `bash`, or similar. 
- Scripts to create mappings for Windows Terminal and add them to the Windows Terminal `settings.json`.

### CODE REVIEW

**Comment by crzdg** [comment]
@luisiacc Do you plan to merge this at some point? 

Let me know if I should change something.

**Comment by luisiacc** [comment]
Hi @crzdg yes I do, sry for the very late reply, this everything looks good, if you can on another PR make a script that will run all of the other scripts for the `extras` folder, at this point if you want you can also make a `Makefile` to run that script, so in a way that if I run `make extras` on cmd, it will regenerate all of the extras files with the latest colors.

**Comment by crzdg** [comment]
@luisiacc This sound like a great idea!
I will try to remember it as soon I will contribute something new.

We probably also have to think of a way to add the colors of the actual Lua-files to the python dict so we don't have to update it manually. Then we have a pretty neat solution to maintain all those extras.

**Comment by luisiacc** [comment]
you can make a lua script to export the colors to a json file, and use the json file as a source of truth for the external scripts that are not in lua, but then on the sequence of scripts you'll have to always run the lua script first to make sure the colors are up-to-date, this is just the idea that is on the top of my mind right now, if you come up with a better one feel free to pursue it.

**Pull request merged**
